
version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - webnet
    volumes:
      - redis-data:/data 
  postgres:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: databasename
    networks:
      - webnet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  web:
    build: .
    # image: webapp
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
networks:
  webnet:
volumes:
  redis-data:
  postgres-data: